#!/usr/bin/env python3
"""Emit src/hipblas_clblast_generated.cc — CLBlast → hipBLAS wrappers.

Run from repo root:
  python3 scripts/gen_clblast_hipblas_wrappers.py > src/hipblas_clblast_generated.cc

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

PREAMBLE = """// AUTO-GENERATED by scripts/gen_clblast_hipblas_wrappers.py — do not edit by hand.
//
// CLBlast-backed hipBLAS wrappers (standard BLAS subset + level-X shad/omatcopy).
//
// SPDX-License-Identifier: MIT

#include "chipblas_internal.hh"
#include "hipblas_clblast_common.hh"

#include <hip/hip_runtime.h>

#include <CL/cl_half.h>

#include <cmath>
#include <cstddef>
#include <cstdint>

using chipblas::BufDir;
using chipblas::Handle;
using chipblas::StagedBuffer;
using hipblas_clblast::asHandle;
using hipblas_clblast::mapDiag;
using hipblas_clblast::mapSide;
using hipblas_clblast::mapTranspose;
using hipblas_clblast::mapTriangle;
using hipblas_clblast::okHandle_stream;
using hipblas_clblast::vecBytesElem;

namespace {

constexpr CLBlastLayout L = CLBlastLayoutColMajor;

template <typename Dispatch>
hipblasStatus_t with1(Handle* h, void* x, size_t xb, Dispatch&& d) {
    if (!okHandle_stream(h)) return HIPBLAS_STATUS_NOT_SUPPORTED;
    if (!x || xb == 0) return HIPBLAS_STATUS_INVALID_VALUE;
    StagedBuffer sx;
    auto st = chipblas::bridgeStage(*h, x, xb, BufDir::INOUT, &sx);
    if (st != HIPBLAS_STATUS_SUCCESS) return st;
    int c = d(sx, h->queue);
    auto wb = chipblas::bridgeWriteBack(*h, sx);
    auto tr = chipblas::translate(c);
    return (tr != HIPBLAS_STATUS_SUCCESS) ? tr : wb;
}

template <typename Dispatch>
hipblasStatus_t with2(Handle* h, const void* x, void* y, size_t xb, size_t yb,
                      BufDir dx, BufDir dy, Dispatch&& d) {
    if (!okHandle_stream(h)) return HIPBLAS_STATUS_NOT_SUPPORTED;
    if (!x || !y || xb == 0 || yb == 0) return HIPBLAS_STATUS_INVALID_VALUE;
    StagedBuffer sx, sy;
    auto st = chipblas::bridgeStage(*h, const_cast<void*>(x), xb, dx, &sx);
    if (st != HIPBLAS_STATUS_SUCCESS) return st;
    st = chipblas::bridgeStage(*h, y, yb, dy, &sy);
    if (st != HIPBLAS_STATUS_SUCCESS) {
        chipblas::bridgeWriteBack(*h, sx);
        return st;
    }
    int c = d(sx, sy, h->queue);
    chipblas::bridgeWriteBack(*h, sx);
    auto wb = chipblas::bridgeWriteBack(*h, sy);
    auto tr = chipblas::translate(c);
    return (tr != HIPBLAS_STATUS_SUCCESS) ? tr : wb;
}

template <typename Dispatch>
hipblasStatus_t with3(Handle* h, const void* a, const void* b, void* c,
                      size_t ab, size_t bb, size_t cb, Dispatch&& d) {
    if (!okHandle_stream(h)) return HIPBLAS_STATUS_NOT_SUPPORTED;
    if (!a || !b || !c || ab == 0 || bb == 0 || cb == 0)
        return HIPBLAS_STATUS_INVALID_VALUE;
    StagedBuffer sa, sb, sc;
    auto st = chipblas::bridgeStage(*h, const_cast<void*>(a), ab, BufDir::IN, &sa);
    if (st != HIPBLAS_STATUS_SUCCESS) return st;
    st = chipblas::bridgeStage(*h, const_cast<void*>(b), bb, BufDir::IN, &sb);
    if (st != HIPBLAS_STATUS_SUCCESS) {
        chipblas::bridgeWriteBack(*h, sa);
        return st;
    }
    st = chipblas::bridgeStage(*h, c, cb, BufDir::INOUT, &sc);
    if (st != HIPBLAS_STATUS_SUCCESS) {
        chipblas::bridgeWriteBack(*h, sa);
        chipblas::bridgeWriteBack(*h, sb);
        return st;
    }
    int err = d(sa, sb, sc, h->queue);
    chipblas::bridgeWriteBack(*h, sa);
    chipblas::bridgeWriteBack(*h, sb);
    auto wb = chipblas::bridgeWriteBack(*h, sc);
    auto tr = chipblas::translate(err);
    return (tr != HIPBLAS_STATUS_SUCCESS) ? tr : wb;
}

} // namespace

extern "C" {

"""


def emit_l1_swap_copy():
    """S/D/C/Z/H swap and copy."""
    out = []
    for ty, name, elem in [
        ("float", "S", "float"),
        ("double", "D", "double"),
        ("hipblasComplex", "C", "hipblasComplex"),
        ("hipblasDoubleComplex", "Z", "hipblasDoubleComplex"),
    ]:
        cl = f"CLBlast{name}swap"
        out.append(
            f"""
hipblasStatus_t hipblas{name}swap(hipblasHandle_t handle, int n,
    {ty}* x, int incx, {ty}* y, int incy) {{
    if (!handle) return HIPBLAS_STATUS_HANDLE_IS_NULLPTR;
    if (incx <= 0 || incy <= 0) return HIPBLAS_STATUS_NOT_SUPPORTED;
    size_t xb = vecBytesElem(n, incx, sizeof({ty}));
    size_t yb = vecBytesElem(n, incy, sizeof({ty}));
    return with2(asHandle(handle), x, y, xb, yb, BufDir::INOUT, BufDir::INOUT,
        [&](StagedBuffer& X, StagedBuffer& Y, cl_command_queue q) {{
            constexpr size_t E = sizeof({ty});
            return {cl}((size_t)n, X.mem, X.offset/E, (size_t)incx,
                Y.mem, Y.offset/E, (size_t)incy, &q, nullptr);
        }});
}}
hipblasStatus_t hipblas{name}copy(hipblasHandle_t handle, int n,
    const {ty}* x, int incx, {ty}* y, int incy) {{
    if (!handle) return HIPBLAS_STATUS_HANDLE_IS_NULLPTR;
    if (incx <= 0 || incy <= 0) return HIPBLAS_STATUS_NOT_SUPPORTED;
    size_t xb = vecBytesElem(n, incx, sizeof({ty}));
    size_t yb = vecBytesElem(n, incy, sizeof({ty}));
    return with2(asHandle(handle), x, y, xb, yb, BufDir::IN, BufDir::OUT,
        [&](StagedBuffer& X, StagedBuffer& Y, cl_command_queue q) {{
            constexpr size_t E = sizeof({ty});
            return CLBlast{name}copy((size_t)n, X.mem, X.offset/E, (size_t)incx,
                Y.mem, Y.offset/E, (size_t)incy, &q, nullptr);
        }});
}}
"""
        )
    # Half
    out.append(
        """
hipblasStatus_t hipblasHswap(hipblasHandle_t handle, int n,
    hipblasHalf* x, int incx, hipblasHalf* y, int incy) {
    if (!handle) return HIPBLAS_STATUS_HANDLE_IS_NULLPTR;
    if (incx <= 0 || incy <= 0) return HIPBLAS_STATUS_NOT_SUPPORTED;
    size_t xb = vecBytesElem(n, incx, sizeof(hipblasHalf));
    size_t yb = vecBytesElem(n, incy, sizeof(hipblasHalf));
    return with2(asHandle(handle), x, y, xb, yb, BufDir::INOUT, BufDir::INOUT,
        [&](StagedBuffer& X, StagedBuffer& Y, cl_command_queue q) {
            return CLBlastHswap((size_t)n, X.mem, X.offset/2u, (size_t)incx,
                Y.mem, Y.offset/2u, (size_t)incy, &q, nullptr);
        });
}
hipblasStatus_t hipblasHcopy(hipblasHandle_t handle, int n,
    const hipblasHalf* x, int incx, hipblasHalf* y, int incy) {
    if (!handle) return HIPBLAS_STATUS_HANDLE_IS_NULLPTR;
    if (incx <= 0 || incy <= 0) return HIPBLAS_STATUS_NOT_SUPPORTED;
    size_t xb = vecBytesElem(n, incx, sizeof(hipblasHalf));
    size_t yb = vecBytesElem(n, incy, sizeof(hipblasHalf));
    return with2(asHandle(handle), x, y, xb, yb, BufDir::IN, BufDir::OUT,
        [&](StagedBuffer& X, StagedBuffer& Y, cl_command_queue q) {
            return CLBlastHcopy((size_t)n, X.mem, X.offset/2u, (size_t)incx,
                Y.mem, Y.offset/2u, (size_t)incy, &q, nullptr);
        });
}
"""
    )
    return "".join(out)


def main() -> None:
    print(PREAMBLE)
    print(emit_l1_swap_copy())
    print("""
} // extern "C"
""")


if __name__ == "__main__":
    main()
